apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: eslamhany17/student-housing-backend:latest
          ports:
            - containerPort: 80
          env:
            - name: APP_ENV
              value: production
            - name: APP_DEBUG
              value: "false"

            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: my-sql-server-database.mysql.database.azure.com
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: student_housing_db
            - name: DB_USERNAME
              value: Eslam
            - name: DB_PASSWORD
              value: TempPass123!